tables:
    path:     /
    defaults: { _controller: "LiuksTableBundle:Table:index" }

table_status:
    path:     /{id}/data
    defaults: { _controller: "LiuksTableBundle:Table:data" }

table_show:
    path:     /{id}/show
    defaults: { _controller: "LiuksTableBundle:Table:show" }

table_new:
    path:     /new
    defaults: { _controller: "LiuksTableBundle:Table:new" }

table_create:
    path:     /create
    defaults: { _controller: "LiuksTableBundle:Table:create" }
    methods:  POST

table_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiuksTableBundle:Table:edit" }

table_update:
    path:     /{id}/update
    defaults: { _controller: "LiuksTableBundle:Table:update" }
    methods:  [POST, PUT]

table_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiuksTableBundle:Table:delete" }
    methods:  [POST, DELETE]
