login_page:
    path: /login
    defaults: { _controller: "LiuksUserBundle:Login:login" }

logout_page:
    path: /logout

liuks_user_users:
    resource: "@LiuksUserBundle/Resources/config/routing/users.yml"
    prefix:   /users