logout_page:
    path: /logout

liuks_user_users:
    resource: "@LiuksUserBundle/Resources/config/routing/users.yml"
    prefix:   /users

liuks_user_teams:
    resource: "@LiuksUserBundle/Resources/config/routing/teams.yml"
    prefix:   /teams