services:
    oauth_user.provider:
        class: Liuks\UserBundle\Auth\OAuthProvider
        calls:
            - [ setContainer, [@service_container] ]

    oauth_user.handler:
        class: Liuks\UserBundle\Auth\AuthHandler
        public: false
        calls:
            - [setRouter, [@router]]