services:
    oauth_user.provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
        class: Liuks\UserBundle\Auth\OAuthProvider
        calls:
            - [ setContainer, [@service_container] ]