hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

liuks_game:
    resource: "@LiuksGameBundle/Resources/config/routing.yml"
    prefix:   /

liuks_table:
    resource: "@LiuksTableBundle/Resources/config/routing.yml"
    prefix:   /

liuks_user:
    resource: "@LiuksUserBundle/Resources/config/routing.yml"
    prefix:   /