users:
    path:     /
    defaults: { _controller: "LiuksUserBundle:Users:index" }

users_show:
    path:     /{id}/show
    defaults: { _controller: "LiuksUserBundle:Users:show" }

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiuksUserBundle:Users:edit" }

users_update:
    path:     /{id}/update
    defaults: { _controller: "LiuksUserBundle:Users:update" }
    methods:  [POST, PUT]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiuksUserBundle:Users:delete" }
    methods:  [POST, DELETE]

users_locator:
    path:     /locator
    defaults: { _controller: "LiuksUserBundle:Users:locator" }

users_closest_table:
    path:     /locator/table
    defaults: { _controller: "LiuksUserBundle:Users:closestTable" }
    methods:  [POST]

users_set_default_table:
    path:     /locator/table/set/{id}
    defaults: { _controller: "LiuksUserBundle:Users:setDefaultTable" }
    methods:  [POST, PUT]