tournaments:
    path:     /
    defaults: { _controller: "LiuksGameBundle:Tournament:index" }

my_tournaments:
    path:     /my
    defaults: { _controller: "LiuksGameBundle:Tournament:myIndex" }

tournament_show:
    path:     /{id}/show
    defaults: { _controller: "LiuksGameBundle:Tournament:show" }

tournament_new:
    path:     /new
    defaults: { _controller: "LiuksGameBundle:Tournament:new" }

tournament_create:
    path:     /create
    defaults: { _controller: "LiuksGameBundle:Tournament:create" }
    methods:  POST

tournament_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiuksGameBundle:Tournament:edit" }

tournament_update:
    path:     /{id}/update
    defaults: { _controller: "LiuksGameBundle:Tournament:update" }
    methods:  [POST, PUT]

tournament_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiuksGameBundle:Tournament:delete" }
    methods:  [POST, DELETE]

tournament_add_player:
    path:     /{id}/add-player
    defaults: { _controller: "LiuksGameBundle:Tournament:addPlayer" }
    methods:  [POST, PUT]

tournament_update_from_json:
    path:     /{id}/data
    defaults: { _controller: "LiuksGameBundle:Tournament:updateFromJson" }