services:
    game_utils.service:
        class: Liuks\GameBundle\Services\GameService
        calls:
            - [setContainer, [@service_container]]
    api_data.service:
        class: Liuks\GameBundle\Services\DataService
