services:
    game_utils.service:
        class: Liuks\GameBundle\Services\GameService
        calls:
            - [setContainer, [@service_container]]
    tournament_utils.service:
        class: Liuks\GameBundle\Services\TournamentService
        calls:
            - [setContainer, [@service_container]]
    api_data.service:
        class: Liuks\GameBundle\Services\DataService
        calls:
            - [setContainer, [@service_container]]


    api_response.listener:
        class: Liuks\GameBundle\EventListeners\ApiResponseEventListener
        tags:
            - { name: kernel.event_listener, event: api_response_error_event, method: onApiResponseError }
            - { name: kernel.event_listener, event: api_response_success_event, method: onApiResponseSuccess }
    game_status.listener:
        class: Liuks\GameBundle\EventListeners\GameStatusEventListener
        tags:
            - { name: kernel.event_listener, event: game_created_event, method: onGameCreate }
            - { name: kernel.event_listener, event: game_over_event, method: onGameOver }
        calls:
            - [setContainer, [@service_container]]
