liuks_table_tables:
    resource: "@LiuksTableBundle/Resources/config/routing/tables.yml"
    prefix:   /tables

liuks_table_homepage:
    path:     /hello/{name}
    defaults: { _controller: LiuksTableBundle:Default:index }
