services:

    table_creation.listener:
        class: Liuks\TableBundle\EventListeners\TableCreationEventListener
        tags:
            - { name: kernel.event_listener, event: table_created_successfully, method: onTableCreate }
        calls:
            - [setContainer, [@service_container]]